name: HHH
favicon: null
layout_spectrum: 0.2589362261351198
typography_spectrum: 0.7087944473605603
title: HHH
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f343a'
    - '#15161b'
    - '#b4b0a5'
    - '#e4e4e2'
    - '#506266'
  brandStrength: 0.48301095282658935
  lightness: 0.7158095757476985
  saturation: 0.09799704188480973
  rhythmicContrast: 0.9916820763610303
purpose: []
